import PDFDocument from 'pdfkit';
import { supabaseAdmin } from '../lib/supabaseAdmin.js';
import { AppError } from '../lib/AppError.js';

// ── Member health card ────────────────────────────────────────

export async function generateMemberHealthCard(memberId, res) {
  const { data: member, error: mErr } = await supabaseAdmin
    .from('members')
    .select('id, full_name, date_of_birth, gender, health_id, abha_id, contact_number, households(malaria_number, village, district, state)')
    .eq('id', memberId)
    .single();
  if (mErr?.code === 'PGRST116') throw new AppError('NOT_FOUND', 'Member not found', 404);
  if (mErr) throw new AppError('INTERNAL', mErr.message, 500);

  const [{ data: vaccinations }, { data: conditions }, { data: pregnancies }] = await Promise.all([
    supabaseAdmin
      .from('vaccinations')
      .select('vaccine_code, status, scheduled_date, administered_date')
      .eq('member_id', memberId)
      .eq('status', 'pending')
      .order('scheduled_date'),
    supabaseAdmin
      .from('disease_history')
      .select('disease_name, status, diagnosed_on')
      .eq('member_id', memberId)
      .eq('status', 'active'),
    supabaseAdmin
      .from('pregnancies')
      .select('status, lmp_date, expected_due_date, risk_level')
      .eq('member_id', memberId)
      .eq('status', 'active'),
  ]);

  const doc = new PDFDocument({ size: 'A5', margin: 40 });
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="health-card-${member.health_id || memberId}.pdf"`);
  doc.pipe(res);

  // Header
  doc.fontSize(18).font('Helvetica-Bold').text('Rural Health Record', { align: 'center' });
  doc.fontSize(11).font('Helvetica').text('Member Health Card', { align: 'center' });
  doc.moveDown(0.5);
  doc.moveTo(40, doc.y).lineTo(doc.page.width - 40, doc.y).stroke();
  doc.moveDown(0.5);

  // Identity
  doc.fontSize(13).font('Helvetica-Bold').text(member.full_name);
  doc.fontSize(10).font('Helvetica');
  if (member.health_id)    doc.text(`Health ID: ${member.health_id}`);
  if (member.abha_id)      doc.text(`ABHA ID: ${member.abha_id}`);
  if (member.date_of_birth) doc.text(`DOB: ${member.date_of_birth}`);
  doc.text(`Gender: ${member.gender === 'M' ? 'Male' : member.gender === 'F' ? 'Female' : 'Other'}`);
  if (member.contact_number) doc.text(`Phone: ${member.contact_number}`);
  doc.moveDown(0.3);

  // Household
  const hh = member.households;
  if (hh) {
    doc.fontSize(10).text(`Household: ${hh.malaria_number}  |  ${hh.village ?? ''}, ${hh.district ?? ''}`);
  }
  doc.moveDown(0.5);

  // Active conditions
  if (conditions?.length) {
    doc.fontSize(11).font('Helvetica-Bold').text('Active Conditions');
    doc.fontSize(10).font('Helvetica');
    conditions.forEach((c) => doc.text(`• ${c.disease_name}  (since ${c.diagnosed_on ?? '—'})`));
    doc.moveDown(0.3);
  }

  // Active pregnancy
  if (pregnancies?.length) {
    const p = pregnancies[0];
    doc.fontSize(11).font('Helvetica-Bold').text('Active Pregnancy');
    doc.fontSize(10).font('Helvetica');
    doc.text(`Risk: ${p.risk_level}  |  LMP: ${p.lmp_date ?? '—'}  |  EDD (ref): ${p.expected_due_date ?? '—'}`);
    doc.moveDown(0.3);
  }

  // Pending vaccinations
  if (vaccinations?.length) {
    doc.fontSize(11).font('Helvetica-Bold').text('Pending Vaccinations');
    doc.fontSize(10).font('Helvetica');
    vaccinations.forEach((v) => doc.text(`• ${v.vaccine_code}  — due ${v.scheduled_date ?? '—'}`));
    doc.moveDown(0.3);
  }

  doc.moveTo(40, doc.y).lineTo(doc.page.width - 40, doc.y).stroke();
  doc.moveDown(0.3);
  doc.fontSize(8).font('Helvetica').fillColor('gray')
    .text('Generated by RuralHealth System. Keep this card safe.', { align: 'center' });

  doc.end();
}

// ── Household health card ─────────────────────────────────────

export async function generateHouseholdHealthCard(householdId, res) {
  const { data: hh, error: hhErr } = await supabaseAdmin
    .from('households')
    .select('id, malaria_number, village, district, state, address_line')
    .eq('id', householdId)
    .single();
  if (hhErr?.code === 'PGRST116') throw new AppError('NOT_FOUND', 'Household not found', 404);
  if (hhErr) throw new AppError('INTERNAL', hhErr.message, 500);

  const { data: members, error: mErr } = await supabaseAdmin
    .from('members')
    .select('id, full_name, date_of_birth, gender, health_id, status')
    .eq('household_id', householdId)
    .eq('status', 'active');
  if (mErr) throw new AppError('INTERNAL', mErr.message, 500);

  // Fetch pending vaccinations + active pregnancies for each member
  const memberIds = members.map((m) => m.id);

  const [{ data: pendingVax }, { data: activePregs }] = await Promise.all([
    supabaseAdmin
      .from('vaccinations')
      .select('member_id, vaccine_code, scheduled_date')
      .in('member_id', memberIds.length ? memberIds : ['00000000-0000-0000-0000-000000000000'])
      .eq('status', 'pending')
      .order('scheduled_date'),
    supabaseAdmin
      .from('pregnancies')
      .select('member_id, risk_level, expected_due_date')
      .in('member_id', memberIds.length ? memberIds : ['00000000-0000-0000-0000-000000000000'])
      .eq('status', 'active'),
  ]);

  const vaxByMember  = {};
  const pregByMember = {};
  (pendingVax  || []).forEach((v) => { vaxByMember[v.member_id]  = [...(vaxByMember[v.member_id]  || []), v]; });
  (activePregs || []).forEach((p) => { pregByMember[p.member_id] = p; });

  const doc = new PDFDocument({ size: 'A4', margin: 40 });
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="household-card-${hh.malaria_number}.pdf"`);
  doc.pipe(res);

  // Header
  doc.fontSize(20).font('Helvetica-Bold').text('Rural Health Record', { align: 'center' });
  doc.fontSize(12).font('Helvetica').text('Family Health Card', { align: 'center' });
  doc.moveDown(0.5);
  doc.moveTo(40, doc.y).lineTo(doc.page.width - 40, doc.y).stroke();
  doc.moveDown(0.5);

  // Household identity
  doc.fontSize(14).font('Helvetica-Bold').text(`Malaria No: ${hh.malaria_number}`);
  doc.fontSize(11).font('Helvetica');
  if (hh.address_line) doc.text(hh.address_line);
  doc.text(`${hh.village ?? ''}, ${hh.district ?? ''}, ${hh.state ?? ''}`);
  doc.moveDown(0.5);

  // Members table
  doc.fontSize(12).font('Helvetica-Bold').text('Members');
  doc.moveDown(0.3);

  members.forEach((m) => {
    const age = m.date_of_birth
      ? Math.floor((Date.now() - new Date(m.date_of_birth)) / (365.25 * 86_400_000))
      : null;

    doc.fontSize(11).font('Helvetica-Bold').text(`${m.full_name}  (${m.gender}${age != null ? `, ${age}y` : ''})`);
    doc.fontSize(10).font('Helvetica');
    if (m.health_id) doc.text(`  Health ID: ${m.health_id}`);

    const preg = pregByMember[m.id];
    if (preg) {
      doc.fillColor('#c05000').text(`  ⚠ Active pregnancy — ${preg.risk_level} risk, EDD (ref): ${preg.expected_due_date ?? '—'}`);
      doc.fillColor('black');
    }

    const vax = vaxByMember[m.id];
    if (vax?.length) {
      doc.text(`  Pending vaccines: ${vax.map((v) => v.vaccine_code).join(', ')}`);
    }

    doc.moveDown(0.3);
  });

  doc.moveTo(40, doc.y).lineTo(doc.page.width - 40, doc.y).stroke();
  doc.moveDown(0.3);
  doc.fontSize(8).font('Helvetica').fillColor('gray')
    .text('Generated by RuralHealth System.', { align: 'center' });

  doc.end();
}
