-- Seed villages for all Maharashtra districts.
-- Uses name-based lookup so district UUIDs are not hardcoded.
INSERT INTO public.villages (district_id, name, verified)
SELECT d.id, v.name, true
FROM public.districts d
JOIN public.states s ON s.id = d.state_id
JOIN (VALUES
  -- Thane
  ('Maharashtra','Thane','Ghansoli'),
  ('Maharashtra','Thane','Airoli'),
  ('Maharashtra','Thane','Vashi'),
  ('Maharashtra','Thane','Nerul'),
  ('Maharashtra','Thane','Belapur'),
  ('Maharashtra','Thane','Kopar Khairane'),
  ('Maharashtra','Thane','Mahape'),
  ('Maharashtra','Thane','Turbhe'),
  ('Maharashtra','Thane','Rabale'),
  ('Maharashtra','Thane','Murbad'),
  ('Maharashtra','Thane','Shahapur'),
  ('Maharashtra','Thane','Wada'),
  ('Maharashtra','Thane','Bhiwandi'),
  ('Maharashtra','Thane','Kalyan'),
  ('Maharashtra','Thane','Titwala'),
  ('Maharashtra','Thane','Atgaon'),
  ('Maharashtra','Thane','Kasara'),
  ('Maharashtra','Thane','Vasind'),
  ('Maharashtra','Thane','Badlapur'),
  ('Maharashtra','Thane','Ulhasnagar'),
  ('Maharashtra','Thane','Dombivli'),
  ('Maharashtra','Thane','Ambernath'),
  ('Maharashtra','Thane','Khardi'),
  ('Maharashtra','Thane','Aasangaon'),
  ('Maharashtra','Thane','Shilphata'),
  -- Pune
  ('Maharashtra','Pune','Baramati'),
  ('Maharashtra','Pune','Shirur'),
  ('Maharashtra','Pune','Daund'),
  ('Maharashtra','Pune','Junnar'),
  ('Maharashtra','Pune','Khed'),
  ('Maharashtra','Pune','Maval'),
  ('Maharashtra','Pune','Lonavala'),
  ('Maharashtra','Pune','Talegaon'),
  ('Maharashtra','Pune','Chakan'),
  ('Maharashtra','Pune','Pirangut'),
  ('Maharashtra','Pune','Mulshi'),
  ('Maharashtra','Pune','Velhe'),
  ('Maharashtra','Pune','Bhor'),
  ('Maharashtra','Pune','Saswad'),
  ('Maharashtra','Pune','Jejuri'),
  ('Maharashtra','Pune','Indapur'),
  ('Maharashtra','Pune','Bhigwan'),
  ('Maharashtra','Pune','Alephata'),
  ('Maharashtra','Pune','Narayangaon'),
  ('Maharashtra','Pune','Ambegaon'),
  ('Maharashtra','Pune','Shirwal'),
  ('Maharashtra','Pune','Lonand'),
  -- Nashik
  ('Maharashtra','Nashik','Igatpuri'),
  ('Maharashtra','Nashik','Ghoti'),
  ('Maharashtra','Nashik','Trimbak'),
  ('Maharashtra','Nashik','Surgana'),
  ('Maharashtra','Nashik','Kalwan'),
  ('Maharashtra','Nashik','Satana'),
  ('Maharashtra','Nashik','Deola'),
  ('Maharashtra','Nashik','Dindori'),
  ('Maharashtra','Nashik','Sinnar'),
  ('Maharashtra','Nashik','Yeola'),
  ('Maharashtra','Nashik','Nifad'),
  ('Maharashtra','Nashik','Chandwad'),
  ('Maharashtra','Nashik','Nandgaon'),
  ('Maharashtra','Nashik','Vani'),
  ('Maharashtra','Nashik','Pimpalgaon'),
  ('Maharashtra','Nashik','Lasalgaon'),
  ('Maharashtra','Nashik','Ojhar'),
  ('Maharashtra','Nashik','Vinchur'),
  ('Maharashtra','Nashik','Manmad'),
  ('Maharashtra','Nashik','Malegaon'),
  -- Nagpur
  ('Maharashtra','Nagpur','Ramtek'),
  ('Maharashtra','Nagpur','Hingna'),
  ('Maharashtra','Nagpur','Umred'),
  ('Maharashtra','Nagpur','Bhiwapur'),
  ('Maharashtra','Nagpur','Katol'),
  ('Maharashtra','Nagpur','Narkhed'),
  ('Maharashtra','Nagpur','Savner'),
  ('Maharashtra','Nagpur','Parseoni'),
  ('Maharashtra','Nagpur','Kamptee'),
  ('Maharashtra','Nagpur','Butibori'),
  ('Maharashtra','Nagpur','Mauda'),
  ('Maharashtra','Nagpur','Kuhi'),
  ('Maharashtra','Nagpur','Kalmeshwar'),
  ('Maharashtra','Nagpur','Wadi'),
  -- Aurangabad
  ('Maharashtra','Aurangabad','Kannad'),
  ('Maharashtra','Aurangabad','Sillod'),
  ('Maharashtra','Aurangabad','Soegaon'),
  ('Maharashtra','Aurangabad','Phulambri'),
  ('Maharashtra','Aurangabad','Vaijapur'),
  ('Maharashtra','Aurangabad','Gangapur'),
  ('Maharashtra','Aurangabad','Khuldabad'),
  ('Maharashtra','Aurangabad','Paithan'),
  ('Maharashtra','Aurangabad','Waluj'),
  ('Maharashtra','Aurangabad','Chikalthana'),
  -- Kolhapur
  ('Maharashtra','Kolhapur','Kagal'),
  ('Maharashtra','Kolhapur','Karvir'),
  ('Maharashtra','Kolhapur','Panhala'),
  ('Maharashtra','Kolhapur','Shahuwadi'),
  ('Maharashtra','Kolhapur','Radhanagari'),
  ('Maharashtra','Kolhapur','Bavda'),
  ('Maharashtra','Kolhapur','Gaganbawada'),
  ('Maharashtra','Kolhapur','Bhudargad'),
  ('Maharashtra','Kolhapur','Ajra'),
  ('Maharashtra','Kolhapur','Chandgad'),
  ('Maharashtra','Kolhapur','Gadhinglaj'),
  ('Maharashtra','Kolhapur','Hatkanangale'),
  ('Maharashtra','Kolhapur','Shirol'),
  ('Maharashtra','Kolhapur','Ichalkaranji'),
  ('Maharashtra','Kolhapur','Jaysingpur'),
  -- Ahmednagar
  ('Maharashtra','Ahmednagar','Shrigonda'),
  ('Maharashtra','Ahmednagar','Pathardi'),
  ('Maharashtra','Ahmednagar','Karjat'),
  ('Maharashtra','Ahmednagar','Shevgaon'),
  ('Maharashtra','Ahmednagar','Rahuri'),
  ('Maharashtra','Ahmednagar','Newasa'),
  ('Maharashtra','Ahmednagar','Sangamner'),
  ('Maharashtra','Ahmednagar','Akole'),
  ('Maharashtra','Ahmednagar','Kopargaon'),
  ('Maharashtra','Ahmednagar','Rahata'),
  ('Maharashtra','Ahmednagar','Parner'),
  ('Maharashtra','Ahmednagar','Jamkhed'),
  ('Maharashtra','Ahmednagar','Nevasa'),
  ('Maharashtra','Ahmednagar','Kedgaon'),
  -- Amravati
  ('Maharashtra','Amravati','Warud'),
  ('Maharashtra','Amravati','Morshi'),
  ('Maharashtra','Amravati','Chandur Bazar'),
  ('Maharashtra','Amravati','Daryapur'),
  ('Maharashtra','Amravati','Anjangaon'),
  ('Maharashtra','Amravati','Achalpur'),
  ('Maharashtra','Amravati','Tivsa'),
  ('Maharashtra','Amravati','Chikhaldara'),
  ('Maharashtra','Amravati','Dharni'),
  ('Maharashtra','Amravati','Bhatkuli'),
  ('Maharashtra','Amravati','Nandgaon Khandeshwar'),
  ('Maharashtra','Amravati','Walgaon'),
  -- Palghar
  ('Maharashtra','Palghar','Dahanu'),
  ('Maharashtra','Palghar','Talasari'),
  ('Maharashtra','Palghar','Jawhar'),
  ('Maharashtra','Palghar','Mokhada'),
  ('Maharashtra','Palghar','Vikramgad'),
  ('Maharashtra','Palghar','Wada'),
  ('Maharashtra','Palghar','Vasai'),
  ('Maharashtra','Palghar','Manor'),
  ('Maharashtra','Palghar','Boisar'),
  ('Maharashtra','Palghar','Safale'),
  ('Maharashtra','Palghar','Vangaon'),
  ('Maharashtra','Palghar','Kelve'),
  ('Maharashtra','Palghar','Aghai'),
  ('Maharashtra','Palghar','Saphale'),
  -- Raigad
  ('Maharashtra','Raigad','Mahad'),
  ('Maharashtra','Raigad','Poladpur'),
  ('Maharashtra','Raigad','Mangaon'),
  ('Maharashtra','Raigad','Roha'),
  ('Maharashtra','Raigad','Alibag'),
  ('Maharashtra','Raigad','Pen'),
  ('Maharashtra','Raigad','Panvel'),
  ('Maharashtra','Raigad','Uran'),
  ('Maharashtra','Raigad','Khalapur'),
  ('Maharashtra','Raigad','Karjat'),
  ('Maharashtra','Raigad','Mhasla'),
  ('Maharashtra','Raigad','Shrivardhan'),
  ('Maharashtra','Raigad','Murud'),
  ('Maharashtra','Raigad','Tala'),
  -- Solapur
  ('Maharashtra','Solapur','Barshi'),
  ('Maharashtra','Solapur','Akkalkot'),
  ('Maharashtra','Solapur','Pandharpur'),
  ('Maharashtra','Solapur','Malshiras'),
  ('Maharashtra','Solapur','Sangola'),
  ('Maharashtra','Solapur','Karmala'),
  ('Maharashtra','Solapur','Madha'),
  ('Maharashtra','Solapur','Mohol'),
  ('Maharashtra','Solapur','Mangalvedhe'),
  ('Maharashtra','Solapur','Akluj'),
  ('Maharashtra','Solapur','Kurduwadi'),
  -- Nanded
  ('Maharashtra','Nanded','Biloli'),
  ('Maharashtra','Nanded','Ardhapur'),
  ('Maharashtra','Nanded','Mudkhed'),
  ('Maharashtra','Nanded','Himayatnagar'),
  ('Maharashtra','Nanded','Hadgaon'),
  ('Maharashtra','Nanded','Kinwat'),
  ('Maharashtra','Nanded','Loha'),
  ('Maharashtra','Nanded','Kandhar'),
  ('Maharashtra','Nanded','Deglur'),
  ('Maharashtra','Nanded','Mukhed'),
  ('Maharashtra','Nanded','Umri'),
  ('Maharashtra','Nanded','Naigaon'),
  ('Maharashtra','Nanded','Bhokar'),
  -- Yavatmal
  ('Maharashtra','Yavatmal','Wani'),
  ('Maharashtra','Yavatmal','Ralegaon'),
  ('Maharashtra','Yavatmal','Ghatanji'),
  ('Maharashtra','Yavatmal','Kelapur'),
  ('Maharashtra','Yavatmal','Pandarkawda'),
  ('Maharashtra','Yavatmal','Ner'),
  ('Maharashtra','Yavatmal','Kalamb'),
  ('Maharashtra','Yavatmal','Darwha'),
  ('Maharashtra','Yavatmal','Umarkhed'),
  ('Maharashtra','Yavatmal','Mahagaon'),
  ('Maharashtra','Yavatmal','Babhulgaon'),
  ('Maharashtra','Yavatmal','Pusad'),
  ('Maharashtra','Yavatmal','Digras'),
  -- Chandrapur
  ('Maharashtra','Chandrapur','Warora'),
  ('Maharashtra','Chandrapur','Chimur'),
  ('Maharashtra','Chandrapur','Bhadravati'),
  ('Maharashtra','Chandrapur','Mul'),
  ('Maharashtra','Chandrapur','Rajura'),
  ('Maharashtra','Chandrapur','Gondpipri'),
  ('Maharashtra','Chandrapur','Korpana'),
  ('Maharashtra','Chandrapur','Nagbhid'),
  ('Maharashtra','Chandrapur','Ballarpur'),
  ('Maharashtra','Chandrapur','Sindewahi'),
  -- Gadchiroli
  ('Maharashtra','Gadchiroli','Chamorshi'),
  ('Maharashtra','Gadchiroli','Mulchera'),
  ('Maharashtra','Gadchiroli','Desaiganj'),
  ('Maharashtra','Gadchiroli','Etapalli'),
  ('Maharashtra','Gadchiroli','Sironcha'),
  ('Maharashtra','Gadchiroli','Aheri'),
  ('Maharashtra','Gadchiroli','Bhamragad'),
  ('Maharashtra','Gadchiroli','Armori'),
  ('Maharashtra','Gadchiroli','Kurkheda'),
  ('Maharashtra','Gadchiroli','Dhanora'),
  ('Maharashtra','Gadchiroli','Korchi'),
  -- Wardha
  ('Maharashtra','Wardha','Arvi'),
  ('Maharashtra','Wardha','Seloo'),
  ('Maharashtra','Wardha','Hinganghat'),
  ('Maharashtra','Wardha','Samudrapur'),
  ('Maharashtra','Wardha','Ashti'),
  ('Maharashtra','Wardha','Deoli'),
  ('Maharashtra','Wardha','Karanja'),
  ('Maharashtra','Wardha','Sindi'),
  -- Latur
  ('Maharashtra','Latur','Udgir'),
  ('Maharashtra','Latur','Nilanga'),
  ('Maharashtra','Latur','Ausa'),
  ('Maharashtra','Latur','Chakur'),
  ('Maharashtra','Latur','Renapur'),
  ('Maharashtra','Latur','Ahmedpur'),
  ('Maharashtra','Latur','Deoni'),
  ('Maharashtra','Latur','Jalkot'),
  ('Maharashtra','Latur','Shirur Anantpal'),
  -- Beed
  ('Maharashtra','Beed','Kaij'),
  ('Maharashtra','Beed','Ambejogai'),
  ('Maharashtra','Beed','Ashti'),
  ('Maharashtra','Beed','Majalgaon'),
  ('Maharashtra','Beed','Parli'),
  ('Maharashtra','Beed','Gevrai'),
  ('Maharashtra','Beed','Patoda'),
  ('Maharashtra','Beed','Shirur Kasar'),
  ('Maharashtra','Beed','Dharur'),
  ('Maharashtra','Beed','Wadwani'),
  -- Jalgaon
  ('Maharashtra','Jalgaon','Bhusawal'),
  ('Maharashtra','Jalgaon','Amalner'),
  ('Maharashtra','Jalgaon','Erandol'),
  ('Maharashtra','Jalgaon','Dharangaon'),
  ('Maharashtra','Jalgaon','Chalisgaon'),
  ('Maharashtra','Jalgaon','Chopda'),
  ('Maharashtra','Jalgaon','Yawal'),
  ('Maharashtra','Jalgaon','Raver'),
  ('Maharashtra','Jalgaon','Pachora'),
  ('Maharashtra','Jalgaon','Parola'),
  ('Maharashtra','Jalgaon','Jamner'),
  ('Maharashtra','Jalgaon','Muktainagar'),
  ('Maharashtra','Jalgaon','Bhadgaon'),
  -- Sangli
  ('Maharashtra','Sangli','Miraj'),
  ('Maharashtra','Sangli','Kupwad'),
  ('Maharashtra','Sangli','Walwa'),
  ('Maharashtra','Sangli','Shirala'),
  ('Maharashtra','Sangli','Tasgaon'),
  ('Maharashtra','Sangli','Palus'),
  ('Maharashtra','Sangli','Jat'),
  ('Maharashtra','Sangli','Atpadi'),
  ('Maharashtra','Sangli','Khanapur'),
  ('Maharashtra','Sangli','Vita'),
  -- Satara
  ('Maharashtra','Satara','Karad'),
  ('Maharashtra','Satara','Wai'),
  ('Maharashtra','Satara','Mahabaleshwar'),
  ('Maharashtra','Satara','Jaoli'),
  ('Maharashtra','Satara','Patan'),
  ('Maharashtra','Satara','Koregaon'),
  ('Maharashtra','Satara','Khatav'),
  ('Maharashtra','Satara','Man'),
  ('Maharashtra','Satara','Phaltan'),
  ('Maharashtra','Satara','Medha'),
  -- Sindhudurg
  ('Maharashtra','Sindhudurg','Malvan'),
  ('Maharashtra','Sindhudurg','Sawantwadi'),
  ('Maharashtra','Sindhudurg','Kudal'),
  ('Maharashtra','Sindhudurg','Devgad'),
  ('Maharashtra','Sindhudurg','Vaibhavwadi'),
  ('Maharashtra','Sindhudurg','Vengurla'),
  ('Maharashtra','Sindhudurg','Dodamarg'),
  ('Maharashtra','Sindhudurg','Kankavli'),
  -- Ratnagiri
  ('Maharashtra','Ratnagiri','Dapoli'),
  ('Maharashtra','Ratnagiri','Khed'),
  ('Maharashtra','Ratnagiri','Chiplun'),
  ('Maharashtra','Ratnagiri','Guhagar'),
  ('Maharashtra','Ratnagiri','Lanja'),
  ('Maharashtra','Ratnagiri','Rajapur'),
  ('Maharashtra','Ratnagiri','Sangameshwar'),
  ('Maharashtra','Ratnagiri','Mandangad'),
  -- Nandurbar
  ('Maharashtra','Nandurbar','Shahada'),
  ('Maharashtra','Nandurbar','Navapur'),
  ('Maharashtra','Nandurbar','Akkalkuwa'),
  ('Maharashtra','Nandurbar','Taloda'),
  ('Maharashtra','Nandurbar','Shirpur'),
  -- Dhule
  ('Maharashtra','Dhule','Sakri'),
  ('Maharashtra','Dhule','Shirpur'),
  ('Maharashtra','Dhule','Sindkheda'),
  ('Maharashtra','Dhule','Shindkheda'),
  -- Buldhana
  ('Maharashtra','Buldhana','Khamgaon'),
  ('Maharashtra','Buldhana','Malkapur'),
  ('Maharashtra','Buldhana','Mehkar'),
  ('Maharashtra','Buldhana','Lonar'),
  ('Maharashtra','Buldhana','Motala'),
  ('Maharashtra','Buldhana','Nandura'),
  ('Maharashtra','Buldhana','Shegaon'),
  ('Maharashtra','Buldhana','Sangrampur'),
  ('Maharashtra','Buldhana','Deulgaon Raja'),
  ('Maharashtra','Buldhana','Jalgaon Jamod'),
  ('Maharashtra','Buldhana','Chikhli'),
  -- Akola
  ('Maharashtra','Akola','Akot'),
  ('Maharashtra','Akola','Telhara'),
  ('Maharashtra','Akola','Balapur'),
  ('Maharashtra','Akola','Patur'),
  ('Maharashtra','Akola','Murtizapur'),
  ('Maharashtra','Akola','Barshitakli'),
  -- Washim
  ('Maharashtra','Washim','Malegaon'),
  ('Maharashtra','Washim','Risod'),
  ('Maharashtra','Washim','Manora'),
  ('Maharashtra','Washim','Karanja'),
  ('Maharashtra','Washim','Mangrulpir'),
  -- Gondia
  ('Maharashtra','Gondia','Arjuni Morgaon'),
  ('Maharashtra','Gondia','Tirora'),
  ('Maharashtra','Gondia','Goregaon'),
  ('Maharashtra','Gondia','Amgaon'),
  ('Maharashtra','Gondia','Sadak Arjuni'),
  ('Maharashtra','Gondia','Salekasa'),
  ('Maharashtra','Gondia','Deori'),
  -- Bhandara
  ('Maharashtra','Bhandara','Tumsar'),
  ('Maharashtra','Bhandara','Pauni'),
  ('Maharashtra','Bhandara','Mohadi'),
  ('Maharashtra','Bhandara','Sakoli'),
  ('Maharashtra','Bhandara','Lakhani'),
  ('Maharashtra','Bhandara','Lakhandur'),
  -- Hingoli
  ('Maharashtra','Hingoli','Basmath'),
  ('Maharashtra','Hingoli','Kalamnuri'),
  ('Maharashtra','Hingoli','Aundha Nagnath'),
  ('Maharashtra','Hingoli','Sengaon'),
  -- Jalna
  ('Maharashtra','Jalna','Badnapur'),
  ('Maharashtra','Jalna','Bhokardan'),
  ('Maharashtra','Jalna','Ghansawangi'),
  ('Maharashtra','Jalna','Ambad'),
  ('Maharashtra','Jalna','Jafarabad'),
  ('Maharashtra','Jalna','Mantha'),
  ('Maharashtra','Jalna','Partur'),
  -- Osmanabad
  ('Maharashtra','Osmanabad','Tuljapur'),
  ('Maharashtra','Osmanabad','Omerga'),
  ('Maharashtra','Osmanabad','Bhoom'),
  ('Maharashtra','Osmanabad','Kalamb'),
  ('Maharashtra','Osmanabad','Paranda'),
  ('Maharashtra','Osmanabad','Umarga'),
  ('Maharashtra','Osmanabad','Washi'),
  -- Parbhani
  ('Maharashtra','Parbhani','Jintur'),
  ('Maharashtra','Parbhani','Manwath'),
  ('Maharashtra','Parbhani','Pathri'),
  ('Maharashtra','Parbhani','Sonpeth'),
  ('Maharashtra','Parbhani','Selu'),
  ('Maharashtra','Parbhani','Gangakhed'),
  ('Maharashtra','Parbhani','Palam'),
  -- Mumbai City
  ('Maharashtra','Mumbai City','Dharavi'),
  ('Maharashtra','Mumbai City','Kurla'),
  ('Maharashtra','Mumbai City','Sion'),
  ('Maharashtra','Mumbai City','Dadar'),
  ('Maharashtra','Mumbai City','Parel'),
  ('Maharashtra','Mumbai City','Matunga'),
  ('Maharashtra','Mumbai City','Chembur'),
  ('Maharashtra','Mumbai City','Mankhurd'),
  ('Maharashtra','Mumbai City','Ghatkopar'),
  ('Maharashtra','Mumbai City','Govandi'),
  -- Mumbai Suburban
  ('Maharashtra','Mumbai Suburban','Borivali'),
  ('Maharashtra','Mumbai Suburban','Dahisar'),
  ('Maharashtra','Mumbai Suburban','Kandivali'),
  ('Maharashtra','Mumbai Suburban','Malad'),
  ('Maharashtra','Mumbai Suburban','Goregaon'),
  ('Maharashtra','Mumbai Suburban','Jogeshwari'),
  ('Maharashtra','Mumbai Suburban','Andheri'),
  ('Maharashtra','Mumbai Suburban','Vile Parle'),
  ('Maharashtra','Mumbai Suburban','Bandra'),
  ('Maharashtra','Mumbai Suburban','Santacruz'),
  ('Maharashtra','Mumbai Suburban','Bhandup'),
  ('Maharashtra','Mumbai Suburban','Mulund'),
  ('Maharashtra','Mumbai Suburban','Powai'),
  ('Maharashtra','Mumbai Suburban','Charkop'),
  ('Maharashtra','Mumbai Suburban','Kurar')
) AS v(state_name, district_name, name)
  ON d.name = v.district_name AND s.name = v.state_name
ON CONFLICT DO NOTHING;

-- Backfill village_id on existing households where text name matches a seeded village in the correct district
UPDATE public.households h
SET village_id = v.id
FROM public.villages v
WHERE h.village_id IS NULL
  AND h.district_id IS NOT NULL
  AND lower(h.village) = lower(v.name)
  AND v.district_id = h.district_id;
